# Generated by Django 3.1.5 on 2021-02-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Jesu Andres', max_length=255),
        ),
    ]
